[package]
name = "animals_canister"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
asset_util = { git = "https://github.com/dfinity/internet-identity.git" }
candid = "0.10"
canister_sig_util = { git = "https://github.com/dfinity/internet-identity.git" }
handlebars = "6.0.0"
ic-cdk = "0.13"
ic-certification = "2.6.0"
include_dir = "0.7.4"
serde = "1.0.209"
serde_json = "1.0.127"
